"""Configuration: a TOML file, or nothing at all.

With no config, NetPulse watches the connection it is running on via the probe — that is
the zero-setup story. A config adds router adapters:

    interval_s = 5

    [[source]]
    name = "mtn"
    kind = "zlt"             # zlt · huawei · zte · starlink · snmp · probe
    url = "http://192.168.0.1"
    # A password is optional and unlocks the connected-device list. It is used only to
    # sign in to this router, is never logged, and never leaves the machine.
    username = "admin"
    password = ""
    # username/password unlock SMS reading (where data-balance texts arrive)

    [[source]]
    name = "airtel-5g"
    kind = "zte"
    url = "http://192.168.0.1"

    [[source]]
    name = "wan"
    kind = "probe"

    [plan]
    limit_gb = 100          # what the plan sells; omit if uncapped
    reset_day = 15          # the day the allowance renews, not necessarily the 1st

    [[alert]]
    metric = "latency.internet_ms"
    above = 300
    for_minutes = 2
    severity = "warning"

    [[alert]]
    metric = "signal.rsrp_dbm"
    below = -105
    for_minutes = 5
    message = "Signal weak enough to drop the connection"

    [[channel]]
    kind = "ntfy"           # webhook · slack · discord · ntfy · home_assistant
    url = "https://ntfy.sh/my-private-topic"

    [[rule]]
    name = "kids tablets"
    kind = "limit"          # limit · schedule · timer
    devices = ["AA:BB:CC:DD:EE:01", "AA:BB:CC:DD:EE:02"]
    limit_gb = 20
    pooled = true           # one shared budget; they run out together
    block = true            # opt-in: without it the rule reports and does not act

    [[rule]]
    name = "bedtime"
    kind = "schedule"
    devices = ["AA:BB:CC:DD:EE:01"]
    windows = [{ from = "22:00", to = "07:00" }]
    block = true
"""

from __future__ import annotations

import tomllib
from contextlib import suppress
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from netpulse.alerting.alerts import Rule, parse_rules
from netpulse.alerting.channels import Channel, parse_channels
from netpulse.analysis.allowance import Plan
from netpulse.analysis.rules import Rule as DataRule
from netpulse.analysis.rules import parse_rules as parse_data_rules

DEFAULT_DIR = Path.home() / ".netpulse"
DEFAULT_CONFIG = DEFAULT_DIR / "netpulse.toml"
DEFAULT_DB = DEFAULT_DIR / "history.db"


@dataclass(frozen=True)
class SourceConfig:
    name: str
    kind: str
    options: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Config:
    sources: tuple[SourceConfig, ...]
    interval_s: float = 5.0
    db_path: Path = DEFAULT_DB
    port: int = 8787
    notifications: bool = True
    plan: Plan = field(default_factory=lambda: Plan())
    alerts: tuple[Rule, ...] = ()
    rules: tuple[DataRule, ...] = ()
    channels: tuple[Channel, ...] = ()


def _plan(raw: Any) -> Plan:
    if not isinstance(raw, dict):
        return Plan()
    limit = raw.get("limit_gb")
    return Plan(
        limit_gb=float(limit) if limit else None,
        reset_day=int(raw.get("reset_day", 1)),
    )


def save_sources(sources: list[SourceConfig], path: Path | None = None) -> Path:
    """Write the source list to the config file — regenerated from what is running,
    which is also what makes it correct."""
    location = path or DEFAULT_CONFIG
    location.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by netpulse; edit freely, it is read at startup", ""]
    for source in sources:
        lines += ["[[source]]", f'name = "{source.name}"', f'kind = "{source.kind}"']
        for key, value in source.options.items():
            if isinstance(value, str):
                lines.append(f'{key} = "{value}"')
            elif isinstance(value, bool):
                lines.append(f"{key} = {str(value).lower()}")
            else:
                lines.append(f"{key} = {value}")
        lines.append("")
    location.write_text("\n".join(lines))
    _protect(location)
    return location


def _protect(location: Path) -> None:
    """Owner-only, like every other file that holds a password.

    A router password in a world-readable file is a router password every account on
    the machine has. Set on write rather than documented, because a permission nobody
    applies is a permission nobody has.
    """
    with suppress(OSError):  # a filesystem without modes is not a reason to fail
        location.chmod(0o600)


def warn_if_exposed(location: Path | None = None) -> str:
    """A message if the config is readable beyond its owner and holds a secret.

    Checked on every start rather than only on write: the file can be created by hand,
    copied from a backup, or restored with someone else's umask.
    """
    path = location or DEFAULT_CONFIG
    try:
        mode = path.stat().st_mode
    except OSError:
        return ""
    if not mode & 0o077:
        return ""
    if "password" not in path.read_text(errors="replace"):
        return ""  # nothing secret in it, so the mode does not matter
    return (
        f"{path} holds a router password and is readable by other accounts on this "
        f"machine (mode {mode & 0o777:o}). Run: chmod 600 {path}"
    )


def load(path: Path | None = None) -> Config:
    location = path or DEFAULT_CONFIG
    if not location.exists():
        return Config(sources=(SourceConfig(name="wan", kind="probe"),))

    data = tomllib.loads(location.read_text())
    sources = tuple(
        SourceConfig(
            name=str(entry.get("name") or entry.get("kind", "source")),
            kind=str(entry["kind"]),
            options={k: v for k, v in entry.items() if k not in ("name", "kind")},
        )
        for entry in data.get("source", [])
    ) or (SourceConfig(name="wan", kind="probe"),)

    return Config(
        sources=sources,
        interval_s=float(data.get("interval_s", 5.0)),
        db_path=Path(data.get("db", DEFAULT_DB)).expanduser(),
        port=int(data.get("port", 8787)),
        notifications=bool(data.get("notifications", True)),
        plan=_plan(data.get("plan", {})),
        alerts=tuple(parse_rules(data.get("alert", []))),
        rules=tuple(parse_data_rules(data.get("rule", []))),
        channels=tuple(parse_channels(data.get("channel", []))),
    )
