"""Configuration: a TOML file, or nothing at all.

With no config, NetPulse watches the connection it is running on via the probe — that is
the zero-setup story. A config adds router adapters:

    interval_s = 5

    [[source]]
    name = "mtn"
    kind = "huawei"          # any carrier's Huawei box: MTN, Airtel, Glo, 9mobile
    url = "http://192.168.8.1"
    # username/password unlock SMS reading (where data-balance texts arrive)

    [[source]]
    name = "airtel-5g"
    kind = "zte"
    url = "http://192.168.0.1"

    [[source]]
    name = "wan"
    kind = "probe"

    [plan]
    limit_gb = 100          # what the plan sells; omit if uncapped
    reset_day = 15          # the day the allowance renews, not necessarily the 1st
"""

from __future__ import annotations

import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

DEFAULT_DIR = Path.home() / ".netpulse"
DEFAULT_CONFIG = DEFAULT_DIR / "netpulse.toml"
DEFAULT_DB = DEFAULT_DIR / "history.db"


@dataclass(frozen=True)
class SourceConfig:
    name: str
    kind: str
    options: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class Plan:
    """A data allowance to measure against. Absent means "just tell me what I used"."""

    #: Gigabytes per cycle, as sold. None when the plan is uncapped or unknown.
    limit_gb: float | None = None
    #: Day of the month the allowance renews. Carriers rarely use the 1st.
    reset_day: int = 1

    @property
    def limit_bytes(self) -> float | None:
        return self.limit_gb * 1_000_000_000 if self.limit_gb else None


@dataclass(frozen=True)
class Config:
    sources: tuple[SourceConfig, ...]
    interval_s: float = 5.0
    db_path: Path = DEFAULT_DB
    port: int = 8787
    notifications: bool = True
    plan: Plan = field(default_factory=lambda: Plan())


def _plan(raw: Any) -> Plan:
    if not isinstance(raw, dict):
        return Plan()
    limit = raw.get("limit_gb")
    return Plan(
        limit_gb=float(limit) if limit else None,
        reset_day=int(raw.get("reset_day", 1)),
    )


def save_sources(sources: list[SourceConfig], path: Path | None = None) -> Path:
    """Write the source list to the config file — regenerated from what is running,
    which is also what makes it correct."""
    location = path or DEFAULT_CONFIG
    location.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# generated by netpulse; edit freely, it is read at startup", ""]
    for source in sources:
        lines += ["[[source]]", f'name = "{source.name}"', f'kind = "{source.kind}"']
        for key, value in source.options.items():
            if isinstance(value, str):
                lines.append(f'{key} = "{value}"')
            elif isinstance(value, bool):
                lines.append(f"{key} = {str(value).lower()}")
            else:
                lines.append(f"{key} = {value}")
        lines.append("")
    location.write_text("\n".join(lines))
    return location


def load(path: Path | None = None) -> Config:
    location = path or DEFAULT_CONFIG
    if not location.exists():
        return Config(sources=(SourceConfig(name="wan", kind="probe"),))

    data = tomllib.loads(location.read_text())
    sources = tuple(
        SourceConfig(
            name=str(entry.get("name") or entry.get("kind", "source")),
            kind=str(entry["kind"]),
            options={k: v for k, v in entry.items() if k not in ("name", "kind")},
        )
        for entry in data.get("source", [])
    ) or (SourceConfig(name="wan", kind="probe"),)

    return Config(
        sources=sources,
        interval_s=float(data.get("interval_s", 5.0)),
        db_path=Path(data.get("db", DEFAULT_DB)).expanduser(),
        port=int(data.get("port", 8787)),
        notifications=bool(data.get("notifications", True)),
        plan=_plan(data.get("plan", {})),
    )
